twitter:
  credentials:
    consumer_key: 'YOUR_INFO'
    consumer_secret: 'YOUR_INFO'
    access_token_key: 'YOUR_INFO'
    access_token_secret: 'YOUR_INFO'
source:
  jsonEndPoint: 'https://fate-srd.com/json'
log: 'tweets.log'
