twitter:
  credentials:
    CONSUMER_KEY: CONSUMER_KEY
    CONSUMER_SECRET: #{process.env.CONSUMER_SECRET}
    ACCESS_TOKEN_KEY: #{process.env.ACCESS_TOKEN_KEY}
    ACCESS_TOKEN_SECRET: #{process.env.ACCESS_TOKEN_SECRET}
source:
  jsonEndPoint: 'https://fate-srd.com/json'
